05 VACE feat: server + frontend (#260)
* feat: add image control

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: evolved image picker infrastructure

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: VACE Infrastructure

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: 257 review

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: add image control

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: evolved image picker infrastructure

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: VACE Longlive + Windows video support

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: VACE StreamDiffusionv2

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* feat: add VACE support to server, front end

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* rename ref_images

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* remove lazy loading

Disabled StreamDiffusion V2V with VACE as I have run out of time.

RuntimeError: Calculated padded input size per channel: (2 x 64 x 64).
Kernel size: (3 x 1 x 1). Kernel size can't be greater than actual input size

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>

* Remove old lazy load VACE code

Left over from merge conflict resolution

Signed-off-by: Yondon Fu <yondon.fu@gmail.com>

* Fix linting error

Signed-off-by: Yondon Fu <yondon.fu@gmail.com>

---------

Signed-off-by: RyanOnTheInside <7623207+ryanontheinside@users.noreply.github.com>
Signed-off-by: Yondon Fu <yondon.fu@gmail.com>
Co-authored-by: Yondon Fu <yondon.fu@gmail.com>